# fly.toml app configuration file generated for shetreks on 2024-03-17T16:03:38+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'shetreks'
primary_region = 'sin'

[build]

[deploy]
  # release_command = "sh /release.sh"

[env]
  PORT = "3000"
  USERNAME = "postgres"
  DATABASE = "shetreks-db"
  HOST = "shetreks-db.internal"
  DIALECT = "postgres"
  NODE_ENV = "production"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
